export const NICHES = [
  "Restaurantes",
  "Pizzarias",
  "Lanchonetes",
  "Cafeterias",
  "Padarias",
  "Açaiterias",
  "Bares e pubs",
  "Hamburguerias",
  "Sorveterias",
  "Food trucks",
  "Salões de beleza",
  "Barbearias",
  "Esmalterias",
  "Clínicas de estética",
  "Clínicas odontológicas",
  "Clínicas médicas",
  "Psicólogos",
  "Nutricionistas",
  "Fisioterapeutas",
  "Academias",
  "Estúdios de pilates",
  "Personal trainers",
  "Pet shops",
  "Clínicas veterinárias",
  "Advogados",
  "Contabilidade",
  "Imobiliárias",
  "Corretores de imóveis",
  "Corretores de seguros",
  "Arquitetos",
  "Designers de interiores",
  "Engenheiros civis",
  "Construtoras",
  "Marcenarias",
  "Serralherias",
  "Eletricistas",
  "Encanadores",
  "Lojas de móveis",
  "Lojas de roupas",
  "Lojas de calçados",
  "Óticas",
  "Joalherias",
  "Floriculturas",
  "Supermercados",
  "Hortifrutis",
  "Açougues",
  "Farmácias",
  "Auto peças",
  "Oficinas mecânicas",
  "Lava jatos",
  "Estética automotiva",
  "Concessionárias",
  "Borracharias",
  "Hotéis e pousadas",
  "Agências de viagens",
  "Buffets e eventos",
  "Cerimonialistas",
  "Fotógrafos",
  "Filmagem de eventos",
  "Escolas particulares",
  "Cursos de idiomas",
  "Escolas de música",
  "Autoescolas",
  "Gráficas",
  "Agências de marketing",
  "Assistência técnica de celulares",
  "Assistência técnica de informática",
  "Dedetizadoras",
  "Empresas de limpeza",
  "Transportadoras",
  "Mudanças e fretes",
] as const;

export const VISUAL_STYLES = [
  "Minimalista",
  "Moderno",
  "Premium / Luxo",
  "Elegante",
  "Clássico",
  "Corporativo",
  "Criativo / Ousado",
  "Divertido / Jovem",
  "Rústico",
  "Industrial",
  "Futurista / Tech",
  "Clean / Claro",
  "Dark / Escuro",
  "Aconchegante",
  "Vintage / Retrô",
  "Feminino",
  "Masculino",
  "Infantil",
  "Esportivo",
  "Natural / Orgânico",
] as const;

export const AUDIENCES = [
  "Público geral",
  "Jovens (18–25)",
  "Adultos (26–40)",
  "Público maduro (40+)",
  "Famílias",
  "Mulheres",
  "Homens",
  "Empresas (B2B)",
  "Alta renda",
  "Público popular",
  "Crianças e pais",
] as const;

export const GOALS = [
  "Gerar orçamentos via WhatsApp",
  "Aumentar vendas online",
  "Receber agendamentos",
  "Apresentar portfólio",
  "Fortalecer a marca",
  "Captar leads / contatos",
  "Divulgar cardápio / catálogo",
  "Mostrar localização e contato",
] as const;

export const SITE_PAGES = [
  "Home",
  "Sobre nós",
  "Serviços",
  "Produtos",
  "Cardápio / Catálogo",
  "Galeria de fotos",
  "Portfólio",
  "Depoimentos",
  "Promoções",
  "Blog",
  "Agendamento",
  "Reservas",
  "Equipe",
  "FAQ / Dúvidas",
  "Localização",
  "Contato",
  "Trabalhe conosco",
  "Política de privacidade",
] as const;

export const CTAS = [
  "Chamar no WhatsApp",
  "Solicitar orçamento",
  "Agendar horário",
  "Fazer pedido",
  "Ligar agora",
  "Visitar a loja",
  "Enviar mensagem",
] as const;

export const STATES: { uf: string; name: string }[] = [
  { uf: "AC", name: "Acre" },
  { uf: "AL", name: "Alagoas" },
  { uf: "AP", name: "Amapá" },
  { uf: "AM", name: "Amazonas" },
  { uf: "BA", name: "Bahia" },
  { uf: "CE", name: "Ceará" },
  { uf: "DF", name: "Distrito Federal" },
  { uf: "ES", name: "Espírito Santo" },
  { uf: "GO", name: "Goiás" },
  { uf: "MA", name: "Maranhão" },
  { uf: "MT", name: "Mato Grosso" },
  { uf: "MS", name: "Mato Grosso do Sul" },
  { uf: "MG", name: "Minas Gerais" },
  { uf: "PA", name: "Pará" },
  { uf: "PB", name: "Paraíba" },
  { uf: "PR", name: "Paraná" },
  { uf: "PE", name: "Pernambuco" },
  { uf: "PI", name: "Piauí" },
  { uf: "RJ", name: "Rio de Janeiro" },
  { uf: "RN", name: "Rio Grande do Norte" },
  { uf: "RS", name: "Rio Grande do Sul" },
  { uf: "RO", name: "Rondônia" },
  { uf: "RR", name: "Roraima" },
  { uf: "SC", name: "Santa Catarina" },
  { uf: "SP", name: "São Paulo" },
  { uf: "SE", name: "Sergipe" },
  { uf: "TO", name: "Tocantins" },
];

export function ufOf(stateName: string): string | undefined {
  return STATES.find((s) => s.name === stateName)?.uf;
}
