export const NICHES = [
  "Restaurantes",
  "Pizzarias",
  "Lanchonetes",
  "Cafeterias",
  "Padarias",
  "Açaiterias",
  "Bares e pubs",
  "Hamburguerias",
  "Salões de beleza",
  "Barbearias",
  "Clínicas de estética",
  "Clínicas odontológicas",
  "Clínicas médicas",
  "Psicólogos",
  "Fisioterapeutas",
  "Academias",
  "Personal trainers",
  "Pet shops",
  "Clínicas veterinárias",
  "Advogados",
  "Contabilidade",
  "Imobiliárias",
  "Corretores de seguros",
  "Arquitetos",
  "Engenheiros civis",
  "Construtoras",
  "Marcenarias",
  "Lojas de móveis",
  "Lojas de roupas",
  "Óticas",
  "Joalherias",
  "Floriculturas",
  "Supermercados",
  "Farmácias",
  "Auto peças",
  "Oficinas mecânicas",
  "Lava jatos",
  "Concessionárias",
  "Hotéis e pousadas",
  "Agências de viagens",
  "Buffets e eventos",
  "Fotógrafos",
  "Escolas particulares",
  "Cursos de idiomas",
  "Autoescolas",
  "Gráficas",
  "Agências de marketing",
  "Assistência técnica",
  "Dedetizadoras",
  "Transportadoras",
] as const;

export const STATES: { uf: string; name: string; cities: string[] }[] = [
  { uf: "AC", name: "Acre", cities: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá"] },
  { uf: "AL", name: "Alagoas", cities: ["Maceió", "Arapiraca", "Palmeira dos Índios", "Rio Largo"] },
  { uf: "AP", name: "Amapá", cities: ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque"] },
  { uf: "AM", name: "Amazonas", cities: ["Manaus", "Parintins", "Itacoatiara", "Manacapuru"] },
  { uf: "BA", name: "Bahia", cities: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna", "Juazeiro", "Ilhéus", "Porto Seguro"] },
  { uf: "CE", name: "Ceará", cities: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral", "Crato", "Itapipoca"] },
  { uf: "DF", name: "Distrito Federal", cities: ["Brasília", "Ceilândia", "Taguatinga", "Águas Claras", "Gama"] },
  { uf: "ES", name: "Espírito Santo", cities: ["Vitória", "Vila Velha", "Serra", "Cariacica", "Linhares", "Guarapari"] },
  { uf: "GO", name: "Goiás", cities: ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia", "Caldas Novas"] },
  { uf: "MA", name: "Maranhão", cities: ["São Luís", "Imperatriz", "Timon", "Caxias", "Codó"] },
  { uf: "MT", name: "Mato Grosso", cities: ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra"] },
  { uf: "MS", name: "Mato Grosso do Sul", cities: ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã"] },
  { uf: "MG", name: "Minas Gerais", cities: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Uberaba", "Governador Valadares", "Ipatinga", "Poços de Caldas"] },
  { uf: "PA", name: "Pará", cities: ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal", "Parauapebas", "Abaetetuba", "Bragança", "Altamira", "Barcarena"] },
  { uf: "PB", name: "Paraíba", cities: ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux"] },
  { uf: "PR", name: "Paraná", cities: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "São José dos Pinhais", "Foz do Iguaçu"] },
  { uf: "PE", name: "Pernambuco", cities: ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Paulista", "Cabo de Santo Agostinho"] },
  { uf: "PI", name: "Piauí", cities: ["Teresina", "Parnaíba", "Picos", "Floriano"] },
  { uf: "RJ", name: "Rio de Janeiro", cities: ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói", "Campos dos Goytacazes", "Petrópolis", "Volta Redonda", "Cabo Frio"] },
  { uf: "RN", name: "Rio Grande do Norte", cities: ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante"] },
  { uf: "RS", name: "Rio Grande do Sul", cities: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Gravataí", "Novo Hamburgo", "São Leopoldo"] },
  { uf: "RO", name: "Rondônia", cities: ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal"] },
  { uf: "RR", name: "Roraima", cities: ["Boa Vista", "Rorainópolis", "Caracaraí"] },
  { uf: "SC", name: "Santa Catarina", cities: ["Florianópolis", "Joinville", "Blumenau", "São José", "Chapecó", "Itajaí", "Criciúma", "Balneário Camboriú"] },
  { uf: "SP", name: "São Paulo", cities: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "Ribeirão Preto", "Sorocaba", "Santos", "São José dos Campos", "Bauru", "Piracicaba"] },
  { uf: "SE", name: "Sergipe", cities: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana"] },
  { uf: "TO", name: "Tocantins", cities: ["Palmas", "Araguaína", "Gurupi", "Porto Nacional"] },
];

export const OTHER = "__outro__";

export function citiesOf(stateName: string): string[] {
  return STATES.find((s) => s.name === stateName)?.cities ?? [];
}
