import { z } from "zod";
import type { BriefingLike } from "@/lib/prompt-templates";

export const generatedSiteSchema = z.object({
  title: z.string().trim().min(1).max(160),
  files: z.object({
    "index.html": z.string().min(1),
    "styles.css": z.string(),
    "script.js": z.string(),
  }),
  previewHtml: z.string().min(1),
});

export type GeneratedSite = z.infer<typeof generatedSiteSchema>;

export function buildPreviewHtml(files: GeneratedSite["files"]): string {
  const css = "<style>" + files["styles.css"] + "</style>";
  const scriptContent = files["script.js"].replaceAll("</script", "<\\/script");
  const script = "<script>" + scriptContent + "</script>";
  let html = files["index.html"];
  html = html.includes("</head>") ? html.replace("</head>", css + "</head>") : css + html;
  html = html.includes("</body>") ? html.replace("</body>", script + "</body>") : html + script;
  return html;
}

export function buildSiteGenerationPrompt(briefing: BriefingLike): string {
  const supplied = Object.entries(briefing)
    .filter(
      ([key, value]) =>
        key !== "id" && value !== null && value !== undefined && String(value).trim(),
    )
    .map(([key, value]) => "- " + key + ": " + String(value).trim())
    .join("\n");

  return `Você é um diretor de criação e desenvolvedor front-end sênior de uma agência brasileira.
Crie um site institucional completo, profissional e pronto para publicar a partir EXCLUSIVAMENTE deste briefing:
${supplied}

Entregue estritamente um objeto JSON com title, files e previewHtml. Em files, inclua exatamente index.html, styles.css e script.js. index.html deve referenciar styles.css e script.js. previewHtml deve ser o HTML autocontido equivalente, com CSS e JavaScript incorporados.

Regras: design clean, premium, mobile-first e responsivo; tipografia legível, espaçamento generoso, acessibilidade básica, meta title/description e HTML semântico. Use as cores e o estilo do briefing. Não invente nomes, preços, avaliações, certificações, horários, contatos, endereço ou serviços. Não use "Generated by AI". Evite neon e excesso de gradientes. A navegação deve funcionar por âncoras. Se houver WhatsApp ou telefone, use apenas o número fornecido; se houver endereço, inclua um link de mapa para ele; inclua formulário somente quando fizer sentido e mantenha-o local (sem envio externo). Não importe bibliotecas, fontes ou imagens externas. Use placeholders CSS discretos em vez de inventar imagens.`;
}
