import { z } from "zod";
import type { BriefingLike } from "@/lib/prompt-templates";

export const generatedSiteSchema = z.object({
  title: z.string().trim().min(1).max(160),
  files: z.object({
    "index.html": z.string().min(1),
    "styles.css": z.string(),
    "script.js": z.string(),
  }),
  previewHtml: z.string().min(1),
});

export type GeneratedSite = z.infer<typeof generatedSiteSchema>;

export function buildPreviewHtml(files: GeneratedSite["files"]): string {
  const css = "<style>" + files["styles.css"] + "</style>";
  const scriptContent = files["script.js"].replaceAll("</script", "<\\/script");
  const script = "<script>" + scriptContent + "</script>";
  let html = files["index.html"];
  html = html.includes("</head>") ? html.replace("</head>", css + "</head>") : css + html;
  html = html.includes("</body>") ? html.replace("</body>", script + "</body>") : html + script;
  return html;
}

export function buildSiteGenerationPrompt(briefing: BriefingLike): string {
  const supplied = Object.entries(briefing)
    .filter(
      ([key, value]) =>
        key !== "id" && value !== null && value !== undefined && String(value).trim(),
    )
    .map(([key, value]) => "- " + key + ": " + String(value).trim())
    .join("\n");

  return `Você é o diretor de criação da KaduDev Studios. Transforme este briefing em uma experiência digital premium e específica para o negócio.

BRIEFING:
${supplied}

ANTES DE CODIFICAR:
1. Identifique mentalmente o nicho, público, principal objetivo comercial e diferencial real.
2. Escolha uma direção de arte coerente com o negócio: paleta, contraste, densidade, formas, ritmo e composição.
3. Planeje uma jornada de conversão clara. O visitante precisa entender em segundos quem é a empresa, o que ela oferece e qual ação deve tomar.
4. Não copie um template conhecido. Faça escolhas visuais deliberadas e diferentes entre nichos.

DIREÇÃO VISUAL OBRIGATÓRIA:
- Hero forte e único, com headline específica ao negócio, CTA principal e composição visual que ocupe o espaço com intenção.
- Hierarquia editorial: eyebrow, títulos expressivos, textos curtos e espaçamento consistente.
- Misture layouts quando fizer sentido: grid, bento, assimetria, split-screen, números, painéis e blocos de destaque.
- Crie uma seção de benefícios/diferenciais e uma seção de serviços/oferta somente quando os dados existirem.
- Termine com uma CTA forte e contextualizada.
- Use uma cor de destaque com neutros; contraste e profundidade antes de efeitos.
- Cards não devem dominar a página. Não transforme cada informação em um card.
- Nada de "site genérico de IA": sem hero roxo/azul previsível, sem excesso de glassmorphism, sem gradiente em tudo, sem 10 cards iguais, sem emojis como decoração.
- Use CSS/SVG inline para criar detalhes visuais originais quando faltarem imagens reais.
- Responsividade: desktop, tablet e mobile devem ter composições intencionais e boa legibilidade.
- Inclua hover/focus/active, microinterações leves e transições rápidas, sem exagero.
- O site precisa parecer finalizado para uma apresentação comercial.

CONTEÚDO E CONFIABILIDADE:
- Use EXCLUSIVAMENTE dados presentes no briefing para fatos sobre a empresa.
- Não invente nomes, preços, avaliações, clientes, números, certificações, horários, contatos, endereço, serviços ou resultados.
- Quando faltar informação, simplifique a seção ou não a inclua; não preencha com Lorem ipsum.
- Escreva em português brasileiro natural, convincente e específico ao nicho.
- Não use "Generated by AI".

TÉCNICA:
- Entregue estritamente JSON com projectName, title e files.
- files deve conter exatamente index.html, styles.css e script.js.
- HTML semântico, meta title/description, viewport, acessibilidade básica e bom contraste.
- Organize CSS com variáveis de cor, espaçamento e radius.
- Navegação por âncoras deve funcionar.
- WhatsApp/telefone devem usar somente números fornecidos. Endereço pode ter link de mapa.
- Formulário, se fizer sentido, deve ser local e não fingir que envia dados.
- Não importe bibliotecas, frameworks, fontes ou imagens externas.
- O index.html deve referenciar styles.css e script.js.`;
}
